// ========== GLOBAL CONSTANTS ==========
const SPREADSHEET_ID = '18N0O0vHScnDbuqpX4yYbUznttsf4wcjyYgdBjHWhQg4';
const ENROLLMENT_TAB = 'ENROLLMENT';
const CARDNUMBER_TAB = 'CARDNUMBER';
const ATTENDANCE_TAB = 'ATTENDANCE';

const STATUS_ACTIVE = 'ACTIVE';
const STATUS_INACTIVE = 'INACTIVE';
